### ISSUE TITLE
Support for declaring fake "forward references" to classes and enums

### ISSUE THREAD

**Issue by MarkGodwin** [AArnott/ImmutableObjectGraph#30]
At the moment, if you add a reference to a user-defined type, it's a battle to get the text templating engine to load in the type to allow it to generate the code based on the inner class. While there are ways to achieve it, it's not very much fun.

If we could supply a fake definition of dependency types defined in the assembly, the TT code would have enough information to understand the type exists to generate the class code. So we could use a pattern like...

    <#@ Include File="..\ImmutableObjectGraph\ImmutableObjectGraph.tt.inc" #>
    <#+
        [ForwardReference]
        class SomeObject { }

        class ImmutableThing
        {
            SomeObject someObjectOrOther;
        }
    #>

`SomeObject` becomes an inner class to the text templater, so allows the `ImmutableThing` definition to compile, and therefore the TT can run without needing to find the true definition of `SomeObject`.

**Comment by MarkGodwin** [comment]
Ha, when I look at the code, I immediately see the `ImmutableObjectGraph.IgnoreAttribute`, which does exactly what I needed, I think

**Comment by MarkGodwin** [comment]
Unfortunately, the attribute can't be applied to enums, but I can fall back to `HiddenTypes.Add(typeof(MyEnum));`

**Comment by AArnott** [comment]
Yes, that's what the `[Ignore]` attribute is for. I'm glad you discovered it. If you send a pull request with a fix so that it works for enums as well, I'll accept it.

That said, T4 is about to be retired in favor of the Roslyn-based approach. In the new Roslyn approach, you don't have to use these stub types because you're allowed to reference other types in your project and referenced assemblies. You also get intellisense as you're typing.

**Comment by AArnott** [comment]
This works with the Roslyn code gen, which will be officially released soon.
