### ISSUE TITLE
Deserialization

### ISSUE THREAD

**Issue by joeizy** [AArnott/ImmutableObjectGraph#42]
How would you handle deserialization? I haven't looked into it much yet but based on my initial thoughts unless you did something fancy like deserialized to the builder type and then called the appropriate "GetImmutable()" method I don't see how you would handle serialization. Am I missing something?

I'm working on an app and I think the pattern would work well with Event Sourcing, CQRS and Actors allowing easy version snapshots to accept out-of-order events and potentially adding multi-threaded access with reader / writer lock constructs except no locks just read most recent snapshot. I need to serialize DTOs over the wire though :\

**Comment by IanYates** [comment]
I wrote some a custom type converter and contract resolver to JSON.NET which does just what you suggest - it deserializes to the builder and then converts to the immutable object.  Works a treat.  I've tailored my immutableObjectGraph somewhat but can try to share what I've done if you're having trouble.  (are you using JSON.NET or something else?)

**Comment by joeizy** [comment]
Haven't gotten to that part of the project yet, but I plan to use Newtonsoft.Json. Depending on the longer term supportability I may wind up going with simple immutable objects but I'd love to see what you have. I don't think I'll really need all of the bells and whistles this template provides. The most important thing for me is that I don't want to completely adopt something that is going to cause more work maintaining than its worth.

All that being said, I'm personally interested in it from a research perspective too.

**Comment by AArnott** [comment]
Would deserialization be easier if a public constructor was defined that took all properties as arguments?

**Comment by IanYates** [comment]
@AArnott - yes.  It probably would be easier, or at least more efficient, than discovering the builder, settings its properties and then invoking the .ToImmutable method via reflection, all whilst convincing something like JSON.Net to take this detour.
I recently found SignalR needed its own tweaking to take that same detour because it resolves parameters differently - just because it can I suppose :)

I'm hoping to finally try out the Roslyn code gen side of things over the break and, depending on how things go, work through to February to do my first ever user group talk based on this library and immutability in general.

**Comment by AArnott** [comment]
Good to get the extra validation. And *do* record your user group talk if you can so we can link to it from here if it's any good. :wink:

https://github.com/dotnet/roslyn/issues/5172 makes me think that having a public constructor with parameter names that exactly match the property names would be a good idea so that these types work well with the possible C# v.future feature of the new `with` keyword for records. No idea if that's the only thing that would be required, but I'd certainly want types generated by this code gen to work well with that. I suspect this project would still be relevant because it's one thing to support immutable records. It's quite a bit more to support immutable object *graphs*, such as this does. #65 tracks this.
