### ISSUE TITLE
Generated class is not public

### ISSUE THREAD

**Issue by dougferg** [AArnott/ImmutableObjectGraph#59]
Roslyn-generated classes are missing the 'public' access modifier at the class declaration.

I may be missing something since I'm just getting started with this project, but are the generated classes purposely being created without the 'public' access modifier?

Generated files appear as:
partial class Fruit
rather than 
public partial class Fruit

The class output by the T4 template DOES output the class with the 'public' access modifier.  Is the different behavior by design?  

Thanks

**Comment by AArnott** [comment]
Yes. It's by design.

In T4, the original code that serves as input into the transformation is not sent to the compiler. So the accessibility modifier needs to propagate. 
In Roslyn code generation, the original code also itself is sent to the compiler. Therefore whatever visibility modifier you specify in your own code will correctly determine the accessibility of the type. The generated code leaves it off because it doesn't want to specify it -- your own code gets to do that.

**Comment by dougferg** [comment]
That did the trick.  

Thanks for the help and for the quick response.
