### ISSUE TITLE
Use in .Net Core project

### ISSUE THREAD

**Issue by nathanwinder** [AArnott/ImmutableObjectGraph#94]
I'm excited to explore Immutable types but I'm having difficulty using them in .Net Core. You mention the requirement to set MSBuild:GenerateCodeFromAttributes in the CustomTool property of the source file that contains the ImmutableTypes. There is no CustomTool field in .Net Core projects, from my understanding this is because .Net Core does not use MSBuild. Is there support for using your tools in .Net Core? If not are there plans to add it?

Thank you,
Nathan

**Comment by AArnott** [comment]
Hi @nathanwinder. .NET Core tooling's next major release will be based on MSBuild. So rather than this project chasing the existing preview tooling, which has no extensibility and in fact makes this type of project impossible, my strategy is to wait for them to come back to msbuild where this will Just Work. :)
